# Generated by Django 4.2.3 on 2023-08-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organisation", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("given_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50)),
                ("family_name", models.CharField(max_length=50)),
                ("full_name", models.CharField(max_length=150)),
                ("address1", models.CharField(max_length=100)),
                ("address2", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=50)),
                ("user_note", models.CharField(max_length=200)),
                ("phone_no", models.IntegerField()),
                ("country", models.CharField(max_length=50)),
            ],
        ),
    ]
